export const navigationItems = [
  {
    title: "Performance",
    href: "/performance",
    eyebrow: "Step 1 · M&B + performance",
    group: "workflow",
    description: "Calculate loading, fuel and runway performance for the selected aircraft before building the operational route.",
    details: ["Mass & balance", "Aerodromes", "PDF export"],
  },
  {
    title: "NavLog",
    href: "/navlog",
    eyebrow: "Step 2 · Route planning",
    group: "workflow",
    description: "Build or reuse a route, apply aircraft and wind data, review fuel and export the NavLog.",
    details: ["Saved routes", "Wind & headings", "Fuel & EFOB"],
  },
  {
    title: "Briefing",
    href: "/briefing",
    eyebrow: "Step 3 · Final package",
    group: "workflow",
    description: "Assemble the final briefing once Performance and NavLog are ready, together with weather, NOTAM, FPL and route documents.",
    details: ["Mission", "Weather & NOTAM", "Final PDF"],
  },
  {
    title: "Area Map",
    href: "/area-map",
    eyebrow: "Utility · NOTAM / GAMET",
    group: "utility",
    description: "Plot coordinate areas, choose what is visible and export the map.",
    details: ["GAMET coordinates", "Saved areas", "PDF map"],
  },
  {
    title: "Aviation Map",
    href: "/vfr-map",
    eyebrow: "Utility · Portugal",
    group: "utility",
    description: "Search aerodromes, VFR points, IFR fixes and navaids on the aviation map.",
    details: ["VFR chart", "Search", "Layers"],
  },
] as const;
